### ISSUE TITLE
Columns broken in 5.4

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/lazylists#5]
Something changed and the columns look fine on the backend but not on the frontend. The classes aren't present at all on the frontend.

**Comment by Mamaduka** [comment]
@nickhamze I can reproduce this issue in WP 5.3.2 as well.

**Comment by nickhamze** [comment]
@Mamaduka 

Weird I'm using it here and the columns work fine:
https://hellofromseattle.com/apps/

But when I try to create a page on the the same site it doesn't work.

I think it means that it broke from 1.0.0 to 1.0.1 as that first list was created with 1.0.0.

Maybe this commit broke it:
https://github.com/sortabrilliant/lazylists/commit/65c8fb38a078b070f658e9595a93ecd60b18466a

**Comment by Mamaduka** [comment]
You're right.

The following condition will always be true for `core/list` block and return `props` without modifications.
```js
if ( typeof props.className === 'undefined' || ! props.className ) {
	return props;
}
```

Unfortunately, my solution also triggers block validation error as mentioned in the #1 issue. I'm not able to find anything in Gutenberg repo that might help us solve the block validation issue.

**Comment by nickhamze** [comment]
What if we created a column style? Would that let us add classes without triggering validation errors?

**Comment by Mamaduka** [comment]
@nickhamze `core/list` block doesn't [support](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/list/index.js#L29) generated class names, so I don't think styles will work with it.

Keeping an eye on this [issue](https://github.com/WordPress/gutenberg/issues/7604) and hopefully some better option will be part of the core.

Currently, we have to provide this bad experience for the users.

**Comment by nickhamze** [comment]
@Mamaduka could we add the classes here somehow. We did that with guidepost in the beginning. 

<img width="276" alt="Screen Shot 2020-03-26 at 10 36 03 AM" src="https://user-images.githubusercontent.com/158918/77665463-b222a000-6f4d-11ea-889c-c33f5e0bb61d.png">

**Comment by Mamaduka** [comment]
@nickhamze pushed the fix, can you test again and also confirm that issue from #1 doesn't happen as well?

**Comment by nickhamze** [comment]
@Mamaduka yeah works well. I screwed up and did the 1.0.1 manually so the repo still says we're on 1.0.0 don't forget to bump it to 1.0.2 before pushing the new version.

**Comment by Mamaduka** [comment]
Changes are deployed to WP.org.
